# SVGO config override 
# https://github.com/svg/svgo

multipass: true
full: true

plugins:
    - addAttributesToSVGElement: false
    - addClassesToSVGElement: false
    - cleanupAttrs: true
    - cleanupEnableBackground: true
    - cleanupIDs: true
    - cleanupListOfValues: true
    - cleanupNumericValues: true
    - collapseGroups: true
    - convertColors: true
    - convertPathData: true
    - convertShapeToPath: false
    - convertStyleToAttrs: true
    - convertTransform: true
    - mergePaths: false
    - minifyStyles: true
    - moveElemsAttrsToGroup: true
    - moveGroupAttrsToElems: true
    - removeAttrs:
        attrs: '(fill|stroke-.*)'
    - removeComments: true
    - removeDesc: true
    - removeDimensions: true
    - removeDoctype: true
    - removeEditorsNSData: true
    - removeElementsByAttr: true
    - removeEmptyAttrs: true
    - removeEmptyContainers: true
    - removeEmptyText: true
    - removeHiddenElems: true
    - removeMetadata: true
    - removeNonInheritableGroupAttrs: true
    - removeRasterImages: true
    - removeStyleElement: true
    - removeTitle: true
    - removeUnknownsAndDefaults: true
    - removeUnusedNS: true
    - removeUselessDefs: true
    - removeUselessStrokeAndFill: true
    - removeViewBox: true
    - removeXMLNS: true
    - removeXMLProcInst: true
    - sortAttrs: true